---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  
  when: ansible_os_family == "Debian"
  tasks:
    - name: Install Nmap
      apt:
        name: nmap
        update_cache: yes
        state: latest
